##################################################
# DATA AND METADATA
##################################################
[id]
run_id = "Bilbo BC034"

[data]
folders = [
    "\\\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF3 Bilbo\\Bilbo 030-on VTC chemistry series\\B034 CO2 in BTB 014 MRe 043\\230524_145000_B034_CO2_injection_15s",
    "\\\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF3 Bilbo\\Bilbo 030-on VTC chemistry series\\B034 CO2 in BTB 014 MRe 043\\230524_162300_B034_rest_150s",
]
results = "E:\\ff_bilbo\\bc034"
baseline = "DSC48955.JPG"

[data.path.baseline]
paths = ["DSC48955.JPG", "DSC48950.JPG", "DSC48940.JPG"]

[protocols]
injection = "protocols/bc034/injection_protocol.csv"                       # note: relative path!
pressure_temperature = "protocols/bc034/pressure_temperature_protocol.csv" # note: relative path!
imaging_mode = "ctime"                                                     # "ctime" or "exif" - only for initialization - "ctime" faster but different!

[protocols.imaging]
"\\\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF3 Bilbo\\Bilbo 030-on VTC chemistry series\\B034 CO2 in BTB 014 MRe 043\\230524_145000_B034_CO2_injection_15s" = "protocols/bc034/imaging_protocol_230524_145000_B034_CO2_injection_15s.csv" # note: relative path!
"\\\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF3 Bilbo\\Bilbo 030-on VTC chemistry series\\B034 CO2 in BTB 014 MRe 043\\230524_162300_B034_rest_150s" = "protocols/bc034/imaging_protocol_230524_162300_B034_rest_150s.csv" # note: relative path!

# Labels based on segmentation of the reference image (e.g., obtained from manual annotation or from a segmentation routine)
[labeling]
colored_image = "./data/bc040/DSC60694_segmented.png"

# Active and inactive corrections
[corrections]

# Type and size correction (for speed)
[corrections.type]
type = "float32"

# TODO: Not supported for now!
#[corrections.resize]
#scale = 0.5

[corrections.drift]
colorchecker = "upper_right"

# Calibration of curvature
[corrections.curvature.crop]
pts_src = [[0, 343], [4437, 322], [4416, 7690], [0, 7669]]
width = 0.92
height = 0.55

