##################################################
# DATA AND METADATA
##################################################
[id]
run_id = "Bilbo reinjection experiment (Gaspard)"

[data]
folder = "D:\\ff\\co2"
results = "D:\\ff_bilbo\\reinjection"
baseline = "DSC51263.JPG"

[data.path.baseline]
paths = ["DSC51263.JPG", "DSC51264.JPG", "DSC51265.JPG"]

[protocols]
imaging = "protocols/reinjection/imaging_protocol.csv"
injection = "protocols/reinjection/injection_protocol.csv"
pressure_temperature = "protocols/reinjection/pressure_temperature_protocol.csv"
imaging_mode = "ctime"                                                     


# Labels based on segmentation of the reference image (e.g., obtained from manual annotation or from a segmentation routine)
[labeling]
colored_image = "./data/reinjection/facies_DSC51263.png"

# Active and inactive corrections
[corrections]

# Type and size correction (for speed)
[corrections.type]
type = "float32"

# TODO: Not supported for now!
#[corrections.resize]
#scale = 0.5

[corrections.drift]
colorchecker = "upper_right"

# Calibration of curvature
[corrections.curvature.crop]
pts_src = [[415, 47], [5263, 110], [5228, 7829], [448, 7886]]
width = 0.92
height = 0.55

# @Thibault uncomment this to test the existing illumination correction in DarSIA
#[corrections.illumination]
#labels = [4] # storage unit
#num_samples = 100

# @Thibault. comment in and out to activate/deactivate your correction - you can only have one of the corrections active
[corrections.patchwise_illumination]
image_path = "D:\\ff\\co2\\DSC51263.JPG" # Note that here you need to use absolute paths
baseline_paths = ["D:\\ff\\co2\\DSC51263.JPG", "D:\\ff\\co2\\DSC51264.JPG"]
# @Thibault: you can control all other parameters you added to the config here.
# limit = 1450
#nw = 1000
#eps= 1e-6
# Note that I removed "show_plot" and "saving_path".
# The former, you can still control in the menu to the left.
# The path is controlled from the workflow. You will need to update your test scripts accordingly.

##################################################
# METADATA
##################################################

# Depth measurements
[depth]
measurements = "./data/constant_depth_measurements.csv"

# Facies properties and mapping to labels in the segmented image
[facies]
props = "./data/facies.csv" # excel file with facies properties

[facies.0] # water and colorchecker
labels = [1, 2]
[facies.1] # caprock
labels = [3]
[facies.2] # storage
labels = [4]

##################################################
# GEOMETRY
##################################################

# Dimensions of the rig
[rig]
dim = 2       # dimension of the model
width = 0.92  # width of the model in m
height = 0.55 # height of the model in m

#[image_porosity]
#mode = "from_image"
#tol = 0.9

# Additional options for from_image mode:
patches = [10, 10]
num_clusters = 5
sample_width = 50
tol_color_distance = 0.1
tol_color_gradient = 0.02

##################################################
# IMAGE PROCESSING
##################################################

# Denoising using a simple averaging filter.
[restoration]
method = "volume_average"

[restoration.options]
rev_size = 0.005 # meters

######################################################
# ROIs
######################################################

[roi.full]
name = "Full Domain"
corner_1 = [0.0, 0.0]
corner_2 = [0.92, 0.55]

[roi.calibration]
name = "full domain without cc"
corner_1 = [0.01, 0.45]
corner_2 = [0.90, 0.00]

# Finger analysis
[roi.fingers]
name = "Fingers in the left storage container associated with port 1"
corner_1 = [0.05, 0.15]
corner_2 = [0.30, 0.00]

[roi.storage]
name = "storage"
corner_1 = [0.0, 0.39]
corner_2 = [0.65, 0.0]

# @Thibault, I defined this calibration ROIs for you. They serve as an example. You could also define others.
# The idea is that the calibration below can be restricted to certain regions of the image only. 
# We could actvely select different regions like the center, far right/left, to stress test
# the calibration, and see whether the color clouds and paths defined through the calibration
# are closer with color correction than without.
[roi.calibration_left]
name = "left part"
corner_1 = [0.0, 0.0] # this has format (x,y) in meters. The dimensions of the rig are listed above in the [rig] section.
corner_2 = [0.45, 0.45]

[roi.calibration_right]
name = "right part"
corner_1 = [0.45, 0.0]
corner_2 = [0.9, 0.45]

######################################################
# DATA SELECTION
######################################################

[data.time.calibration]
times = ["00:15:00", "01:00:00", "02:00:00",]

[data.interval.injection]
start = "00:00:00"
end = "01:00:00"
num = 25
tol = "00:05:00"

[data.interval.analysis]
start = "01:00:00"
end = "48:00:00"
num = 48
tol = "00:05:00"

#####################################
# SIGNALS
#####################################

[color.path.color_path]
# @Thibault: you could also switch to "auto" here, "manual" allows to define your own color paths (used if the "wls" method below is not satisfactory)
calibration_mode = "auto" # "manual"
# @Thibault: redo the procedure for different ROIs "calibration_left", "calibration_right", "calibration"
rois = ["calibration"]
# @Thibault: These are tuning parameters, it may be interesting to play with those, not sure what instructions to give you really, but I try
threshold_calibration = 0.0 # Main control parameter on the color cloud. Lower values should increase the sensitivity to pick up colors. So far I always needed to use high values (1e-3 typically) as the color cloud was too noisy. Here you should test values: 0.0, 1e-5, 1e-4, 1e-3. Primary priority.
num_segments = 3 # this controls how many segments the color paths have - 6 is too high. I would try values: 2,3,4.
histogram_weighting = "wls" # This selects the algorithm used to decide the automatic path selection. I typically always use "wls", so secondary priority. available algorithms: "threshold", "wls", "wls_sqrt", "wls_log"
resolution = 21 # needs to be odd, could also try 31 and 41 (low priority)
threshold_baseline = 0.0 # should stay 0.
# @Thibault: Do not need to touch from here on.
data = ["calibration"]
baseline = "baseline"
mode = "relative"
basis = "facies"
ignore_baseline_spectrum = "none"
ignore_labels = [0] # water and top layer
reference_label = 2 # Main storage layer


[calibration]
data = ["calibration"]

[calibration.color]
color = "color_path"
# TODO: move data from color paths here...

[calibration.mass]
data = "calibration" # TODO rm.
color = "color_path"

#####################################
# ANALYSIS
#####################################

[analysis]
data = ["injection", "analysis"]
formats = ["jpg", "npz", "csv"] #["jpg", "csv"]

[analysis.fingers]
mode = "concentration_aq" # Choose from std modes ("mass", "concentration_aq", ...) or "id" among color.*.<id>.
threshold = 0.01 # Choose sufficiently low.
roi = ["storage"] # Choose such that the top boundary crosses the plume.

# Options for simplifying the analyzed contour
reduce_to_main_contour = true # If true, removes all small features.
fill_holes = false # If true, holes in segmentation will be filled.

# Smoothing of the contour
contour_smoother = "savitzky_golay" # If chosen, contours are smoothed.
[analysis.fingers.contour_smoother_options]
window_length = 41
polyorder = 3

[analysis.mass]
color = "color_path"
export = ["mass", "rescaled_saturation_g", "rescaled_concentration_aq", "saturation_g", "concentration_aq"]

#[analysis.expert_knowledge]
#saturation_g = ["storage"]
#rescaled_saturation_g = ["storage"]
#concentration_aq = ["storage", "caprock"]
#rescaled_concentration_aq = ["storage", "caprock"]

[analysis.segmentation.aqueous]
label = "CO2(aq)"
mode = "concentration_aq"
thresholds = [0.02, 0.1, 0.3, 0.5, 0.7, 0.9]
color = [114, 243, 185]
alpha = [0.05, 0.1, 0.3, 0.5, 0.7, 0.9]
linewidth = 16
show_values = false
value_color = [255, 255, 255]
value_size = 4
value_alpha = 0.5
value_density = 0.5
value_min_distance_px = 35
value_max_per_contour = 4
value_format = "{:.2f}"

[analysis.segmentation.gas]
label = "CO2(g)"
mode = "rescaled_saturation_g"
thresholds = [0.01, 0.5, 0.9]
color = [255, 243, 137]
alpha = [0.25, 0.5, 1.0]
linewidth = 16

#####################################
# HELPER
#####################################

[helper.roi]
data = "calibration"

[helper.roi_viewer]
data = "calibration"

[helper.results]
data = "calibration"
mode = "extensive_rescaled_mass"
format = "csv"

#####################################
# FORMATS
#####################################

[format.jpg.jpg]
resolution = [1080, 4]
keep_ratio = true
name = "spatial_map_HH:MM"
cmap = "color_path.from_facies.7"
quality=100

[format.csv.csv]
resolution = [220, 368]
keep_ratio = false
float_format = "{:.3e}"
name = "spatial_map_HH:MM"

[format.npz.npz]
name = "spatial_map_HH:MM"

#####################################
# UTILS
#####################################

# For download of raw images to local filesystem
#[download]
#source = "\\\\klient.uib.no\\FELLES\\LAB-IT\\IFT\\resfys\\FluidFlower\\FF2 24-25 glass beads\\050825_glass_beads_1_150_s"

[video]

[video.source]
#folder = "segmentation/jpg" # relative to [data.results] when not absolute
#folder = "mass/jpg" # relative to [data.results] when not absolute
#folder = "saturation_g/jpg" # relative to [data.results] when not absolute
#folder = "concentration_aq/jpg" # relative to [data.results] when not absolute
folder = "cropping/jpg" # relative to [data.results] when not absolute
#folder = "fingers/paths/storage" # relative to [data.results] when not absolute
#folder = "fingers/tips/storage" # relative to [data.results] when not absolute
#extensions = [".jpg"]
recursive = false
sorting = "name"

[video.output]
formats = ["mp4"]
fps = 6.0
codec = "mp4v"
quality = 100
# resolution = [1280, 720] # optional [width, height]

[video.overlay]
show_elapsed_time = false
elapsed_time_format = "Elapsed: {:.2f} h"
show_note = true
note = "FluidFlower BC02"
font_scale = 0.5
thickness = 2
text_color = [255, 255, 255]
position = [20, 20]
box_enabled = true
box_color = [0, 0, 0]
box_alpha = 0.4
box_padding = 10

